<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>Assets\clock-icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.0.13" />
    <PackageReference Include="Avalonia.Controls.ColorPicker" Version="11.0.13" />
    <PackageReference Include="Avalonia.Desktop" Version="11.0.13" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.0.13" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.0.13" />
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>
</Project>
